version: 2.0
workflows:
  build-android-ios:
    name: Build Android and iOS
    environment:
      flutter: stable
      xcode: "13.2" # تغيير إصدار إكسكود إلى 13.2
      cocoapods: default
    scripts:
      - flutter packages pub get
      - flutter format --set-exit-if-changed .
      - flutter analyze
      - flutter test
      - flutter build apk --debug --no-codesign
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - ameenmamwn7@gmail.com
