name: Extract mobileprovision Content

on:
  push:
    branches: [ master ]

jobs:
  extract_content:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Extract mobileprovision content
      run: |
        plutil -convert xml1 -o extracted_mobileprovision.plist profile1.mobileprovision
        plutil -p extracted_mobileprovision.plist > profile1.mobileprovision.txt
