- name: Install CocoaPods
  run: sudo gem install cocoapods

- name: Clean CocoaPods cache
  run: pod cache clean --all

- name: Install CocoaPods dependencies
  run: |
    cd ios
    pod install
